/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
*/
function getFibs(num) {
	let arr = [];
	let n2 = 1, nextTerm;

	for (let i = 1; i < num; ) {
		arr.push(i);
		nextTerm = i + n2;
		i = n2;
		n2 = nextTerm;
	}
	return arr;
}

function sumFibs(num){
  let sum = 0;
  let fibs = getFibs(num);

  for (let i = 0; i < fibs.length; i++) {
    if (fibs[i] % 2 == 0){
      sum += fibs[i];
    }
  }
  return sum;
}

console.log(sumFibs()); 
