/* Each new term in the Fibonacci sequence is generated by adding the
previous two terms. by starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

by considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms
*/

#include <iostream>

int main() {
  long sum = 2, n1 = 1, n2 = 2, nextTerm = 0; 

  while (nextTerm < 4000000) {
    if (nextTerm % 2 == 0) {
      sum += nextTerm; 
    }
    nextTerm = n1 + n2; 
    n1 = n2; 
    n2 = nextTerm; 
  }

  std::cout << sum << std::endl; 
  return 0; 
}
